//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public long id { get; set; }
        public string name { get; set; }
        public string text { get; set; }
        public long id_user { get; set; }
    
        public virtual user user { get; set; }
    }
}
